<?php

namespace DMD\CoffeeBundle\Repository;

/**
 * InventoryMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryMonthRepository extends \Doctrine\ORM\EntityRepository
{
}
