<?php

namespace DMD\CoffeeBundle\Repository;

/**
 * InventoryReceivingVoucherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventoryReceivingVoucherRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDates($from_date, $to_date) {
        
        $queryBuilder = $this->createQueryBuilder('o');
        $queryBuilder
                ->where("o.createdAt > :from_date")
                ->andWhere("o.createdAt < :to_date")
                ->setParameter('from_date',$from_date)
                ->setParameter('to_date',$to_date)
                ;
        return $queryBuilder->getQuery()->getResult();
    }
    
}
