<?php

namespace DMD\CoffeeBundle\Repository;

/**
 * UnitReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
